[package]
name = "aula-facil"
version = "0.4.12"
description = "Aplicativo desktop do AulaFácil"
authors = ["AulaFácil"]
edition = "2021"

[lib]
name = "aula_facil_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["dpapi", "winbase", "wincrypt"] }




