import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]!))}
function money(v:unknown){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0)}
function html(body:string,status=200){return new Response(body,{status,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","Content-Security-Policy":"default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"}})}
function page(title:string,content:string,primary="#1649b8"){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>:root{--p:${/^#[0-9a-f]{6}$/i.test(primary)?primary:"#1649b8"}}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#eef1f4;color:#18202c;padding:28px}.wrap{max-width:620px;margin:0 auto}.card{background:#fff;border:1px solid #d9dee6;border-radius:22px;padding:26px;box-shadow:0 12px 34px rgba(20,31,50,.08)}.brand{display:flex;align-items:center;gap:14px;margin-bottom:24px}.logo{width:58px;height:58px;border-radius:16px;display:grid;place-items:center;background:var(--p);color:white;font-weight:800;overflow:hidden}.logo img{width:100%;height:100%;object-fit:contain;background:white}.brand h1{font-size:20px;margin:0}.brand p{margin:3px 0 0;color:#647084}.info{display:grid;gap:10px;padding:16px;border-radius:16px;background:#f6f7f9;margin-bottom:20px}.row{display:flex;justify-content:space-between;gap:18px}.row span{color:#6c7686}.row strong{text-align:right}.paid{padding:18px;border-radius:16px;background:#e9f8ef;color:#176b3a;font-weight:700;text-align:center}.warning{padding:13px 15px;border-radius:14px;background:#fff7e6;color:#7a4b00;margin-bottom:16px;font-size:13px}.methods{display:grid;gap:16px}.method{border:1px solid #dde2e9;border-radius:16px;padding:18px}.method h2{font-size:17px;margin:0 0 12px}.qr{display:block;width:min(260px,100%);margin:8px auto 14px;border-radius:10px}.code{width:100%;min-height:76px;padding:12px;border:1px solid #d9dee6;border-radius:12px;background:#fafbfc;word-break:break-all;font-size:12px}.btn{display:block;width:100%;border:0;border-radius:12px;padding:13px 16px;background:var(--p);color:white;text-decoration:none;text-align:center;font-weight:700;cursor:pointer;margin-top:10px}.secondary{background:#e9edf3;color:#202936}.small{font-size:12px;color:#6b7484;text-align:center;margin-top:18px}@media(max-width:520px){body{padding:14px}.card{padding:20px}.row{display:block}.row strong{display:block;text-align:left;margin-top:3px}}</style></head><body><div class="wrap"><div class="card">${content}</div></div></body></html>`}

Deno.serve(async(req:Request)=>{
 const u=new URL(req.url),token=(u.searchParams.get("t")??"").trim();if(!/^[0-9a-f]{64}$/i.test(token))return html(page("Link inválido","<div class='paid'>Este link de pagamento é inválido.</div>"),404);
 const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!supabaseUrl||!serviceKey)return html(page("Indisponível","<div class='paid'>Pagamento temporariamente indisponível.</div>"),503);
 const db=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
 const {data:link}=await db.from("payment_links").select("*, invoice:invoices(*, student:students(*), school:schools(*))").eq("token",token).maybeSingle();
 if(!link||link.revoked_at||(link.expires_at&&new Date(link.expires_at)<new Date()))return html(page("Link expirado","<div class='paid'>Este link não está mais disponível. Solicite uma nova cobrança à escola.</div>"),410);
 const invoice:any=Array.isArray((link as any).invoice)?(link as any).invoice[0]:(link as any).invoice;if(!invoice)return html(page("Cobrança indisponível","<div class='paid'>Cobrança não encontrada.</div>"),404);
 const student:any=Array.isArray(invoice.student)?invoice.student[0]:invoice.student,school:any=Array.isArray(invoice.school)?invoice.school[0]:invoice.school;
 const meta:any=invoice.provider_metadata&&typeof invoice.provider_metadata==="object"?invoice.provider_metadata:{};
 const {data:dueRows}=await db.rpc("invoice_amount_due",{target_invoice:invoice.id,as_of:new Date().toISOString().slice(0,10)}),due:any=Array.isArray(dueRows)?dueRows[0]:dueRows;
 const dynamicAmount=Number(due?.total_due??invoice.amount),generatedAmount=Number(meta.amount??0),hasProviderCharge=Boolean(invoice.provider_charge_id);
 const amount=hasProviderCharge&&Number.isFinite(generatedAmount)&&generatedAmount>0?generatedAmount:dynamicAmount;
 const amountLabel=hasProviderCharge?"Valor desta cobrança":"Valor atualizado";
 const schoolName=esc(school?.name||"Instituição"),logo=school?.logo_url?`<img src="${esc(school.logo_url)}" alt="">`:esc(String(school?.name||"A").trim().slice(0,2).toUpperCase()),brand=`<div class="brand"><div class="logo">${logo}</div><div><h1>${schoolName}</h1><p>Pagamento seguro</p></div></div>`;
 const details=`<div class="info"><div class="row"><span>Aluno</span><strong>${esc(student?.name||"Aluno")}</strong></div><div class="row"><span>Referência</span><strong>${esc(invoice.reference)}</strong></div><div class="row"><span>Vencimento</span><strong>${esc(new Date(`${invoice.due_date}T12:00:00`).toLocaleDateString("pt-BR"))}</strong></div><div class="row"><span>${amountLabel}</span><strong>${money(amount)}</strong></div></div>`;
 if(invoice.status==="paid")return html(page("Pagamento confirmado",`${brand}${details}<div class="paid">✓ Pagamento confirmado. Obrigado!</div><div class="small">O recibo fica registrado no AulaFácil da instituição.</div>`,school?.primary_color));
 if(["cancelled","negotiated"].includes(invoice.status))return html(page("Cobrança indisponível",`${brand}${details}<div class="paid">Esta cobrança não está disponível para pagamento.</div>`,school?.primary_color),409);
 let methods="",pixCode=invoice.pix_copy_paste||meta.manualPixKey||"";
 if(invoice.pix_qr_code_base64||pixCode){const qr=invoice.pix_qr_code_base64?`<img class="qr" alt="QR Code Pix" src="data:image/png;base64,${esc(invoice.pix_qr_code_base64)}">`:"",copy=pixCode?`<textarea id="pix" class="code" readonly>${esc(pixCode)}</textarea><button class="btn" onclick="navigator.clipboard.writeText(document.getElementById('pix').value).then(()=>this.textContent='Copiado ✓')">Copiar Pix</button>`:"";methods+=`<div class="method"><h2>Pix</h2>${qr}${copy}</div>`}
 if(invoice.boleto_url)methods+=`<div class="method"><h2>Boleto</h2><a class="btn" rel="noopener noreferrer" target="_blank" href="${esc(invoice.boleto_url)}">Abrir boleto</a></div>`;
 if(invoice.payment_url)methods+=`<div class="method"><h2>Pagamento online</h2><a class="btn secondary" rel="noopener noreferrer" target="_blank" href="${esc(invoice.payment_url)}">Abrir página do provedor</a></div>`;
 const artifactWarning=typeof meta.artifactWarning==="string"&&meta.artifactWarning?`<div class="warning">A cobrança foi criada no provedor, mas um dos dados de exibição ainda está sendo recuperado. Você pode usar a página do provedor quando disponível.</div>`:"";
 if(!methods)methods=`<div class="paid">A cobrança existe, mas os dados de pagamento ainda estão sendo recuperados. Entre em contato com a escola antes de tentar pagar.</div>`;
 return html(page(`${school?.name||"AulaFácil"} - ${invoice.reference}`,`${brand}${details}${artifactWarning}<div class="methods">${methods}</div><div class="small">Este link é exclusivo desta cobrança. Não compartilhe publicamente.</div>`,school?.primary_color));
});